# Generated by Django 5.1.3 on 2024-11-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_note_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.TextField(default='#ffdcbd', max_length=9),
        ),
        migrations.AddField(
            model_name='note',
            name='pos_left',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='note',
            name='pos_top',
            field=models.IntegerField(default=50),
        ),
    ]
