# Generated by Django 5.1.3 on 2024-11-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_note_color_note_pos_left_note_pos_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='pos_left',
            field=models.TextField(default='20px', max_length=7),
        ),
        migrations.AlterField(
            model_name='note',
            name='pos_top',
            field=models.TextField(default='20px', max_length=7),
        ),
    ]
