# Generated by Django 5.1.1 on 2024-12-09 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_note_pos_left_alter_note_pos_top'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline_Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.note')),
            ],
        ),
    ]
